"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
import {cartCount} from "../lib/cart";

type Product={id:string;name:string;price:number;compare_at_price:number|null;images:string[]|null;stock:number;sku:string|null;is_active:boolean};
type Content={content_key:string;value:string};
const categories=["Sarees","Suits & Sets","Kurtis","Dresses"];

export default function Home(){
 const [searchOpen,setSearchOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[query,setQuery]=useState(""),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[bagItems,setBagItems]=useState(0),[content,setContent]=useState<Record<string,string>>({});
 useEffect(()=>{(async()=>{const [{data:productsData},{data:contentData}]=await Promise.all([supabase.from("products").select("id,name,price,compare_at_price,images,stock,sku,is_active").eq("is_active",true).order("created_at",{ascending:false}).limit(12),supabase.from("store_content").select("content_key,value")]);setProducts((productsData as Product[])??[]);const map:Record<string,string>={};((contentData as Content[])??[]).forEach(x=>map[x.content_key]=x.value);setContent(map);setLoading(false)})()},[]);
 useEffect(()=>{const update=()=>setBagItems(cartCount());update();window.addEventListener("arvind-cart-updated",update);window.addEventListener("storage",update);return()=>{window.removeEventListener("arvind-cart-updated",update);window.removeEventListener("storage",update)}},[]);
 const c=(key:string,fallback:string)=>content[key]?.trim()||fallback;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?products.filter(p=>p.name.toLowerCase().includes(q)||(p.sku??"").toLowerCase().includes(q)):products},[products,query]);
 return <main>
  <div className="topbar"><span>{c("announcement","✨ Festive collection is coming soon")}</span><span className="topbar-sep">•</span><span>Free delivery on selected orders</span><span className="topbar-location">Mandsaur, Madhya Pradesh</span></div>
  <header className="nav"><div className="container nav-inner"><button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenuOpen(!menuOpen)}>☰</button><a className="logo" href="#"><span>ARVIND</span><small>DRESSES</small></a><nav className={menuOpen?"nav-links mobile-open":"nav-links"}><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#offers">Offers</a><a href="#about">Our Story</a><a href="#contact">Contact</a></nav><div className="nav-actions"><button className="icon-btn" aria-label="Search" onClick={()=>setSearchOpen(!searchOpen)}>⌕ <span>Search</span></button><a className="icon-btn bag-btn" aria-label="Shopping bag" href="/cart">♧ <span>Bag</span>{bagItems>0&&<b>{bagItems}</b>}</a></div></div>{searchOpen&&<div className="search-panel"><div className="container"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sarees, kurtis, suits..."/></div></div>}</header>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">ARVIND DRESSES • MANDSAUR</div><h1>{c("hero_title","Every outfit. A little more you.")}</h1><p>{c("hero_text","Discover thoughtfully selected ethnic and contemporary fashion for celebrations, everyday moments and everything in between.")}</p><div className="hero-actions"><a className="cta" href="#shop">Shop new arrivals <span>→</span></a><a className="text-link" href="#categories">Explore collections</a></div><div className="trust-row"><span>✓ Curated styles</span><span>✓ Easy ordering</span><span>✓ Reliable delivery</span></div></div><div className="hero-visual">{content.hero_image?<div className="hero-art" style={{backgroundImage:`url(${content.hero_image})`,backgroundSize:"cover",backgroundPosition:"center"}}/>:<div className="hero-art"><div className="art-label"><small>THE NEW EDIT</small><strong>Festive<br/>2026</strong><span>Coming soon</span></div><div className="art-shape one"/><div className="art-shape two"/><div className="art-shape three"/></div>}<div className="floating-note"><span>01</span><div><b>Made for moments</b><small>From Mandsaur, with style.</small></div></div></div></div></section>
  <section className="benefits"><div className="container benefits-grid"><div><span>01</span><b>Fresh collections</b><small>New styles added regularly</small></div><div><span>02</span><b>Easy ordering</b><small>Simple, secure checkout</small></div><div><span>03</span><b>Reliable delivery</b><small>Shipped with care</small></div><div><span>04</span><b>Local support</b><small>We&apos;re here when you need us</small></div></div></section>
  <section className="section" id="categories"><div className="container"><div className="section-head"><div><div className="eyebrow">01 / Collections</div><h2>Find your next favourite.</h2></div><a className="text-link" href="#shop">View all →</a></div><div className="categories">{categories.map((cat,i)=><a className={`category category-${i+1}`} href="#shop" key={cat}><div className="category-art"><span>0{i+1}</span></div><div className="category-copy"><small>{["Elegant & festive","Ready-to-wear","Everyday style","Modern looks"][i]}</small><strong>{cat}</strong><span>Shop collection →</span></div></a>)}</div></div></section>
  <section className="section products-section" id="shop"><div className="container"><div className="section-head"><div><div className="eyebrow">02 / The edit</div><h2>{c("shop_title","What&apos;s catching eyes.")}</h2></div><span className="muted">Live collection • Updated from our store</span></div>{c("shop_text","")&&<p className="muted" style={{maxWidth:650,marginTop:-18,marginBottom:25}}>{content.shop_text}</p>}{loading?<p className="muted">Loading the latest collection…</p>:filtered.length===0?<div className="panel empty-panel"><div className="empty-icon">✦</div><h2>{query?"No products found":"New collection coming soon"}</h2><p>{query?"Try another search.":"Add products from the Admin panel and they will appear here automatically."}</p></div>:<div className="products">{filtered.map((p,i)=><article className="product" key={p.id}><a className={`product-image product-image-${i%4+1}`} href={`/product/${p.id}`}><div>{p.images?.[0]?<img src={p.images[0]} alt={p.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div className="product-placeholder"><span>ARVIND</span><small>PRODUCT IMAGE</small></div>}</div><span className="product-tag">{p.stock>0?"AVAILABLE":"SOLD OUT"}</span></a><div className="product-body"><a href={`/product/${p.id}`}><h3>{p.name}</h3></a><div><span className="price">₹{Number(p.price).toLocaleString("en-IN")}</span>{p.compare_at_price?<span className="old">₹{Number(p.compare_at_price).toLocaleString("en-IN")}</span>:null}</div><small>{p.stock>0?`${p.stock} in stock`:"Currently unavailable"}</small><a className="product-add" href={`/product/${p.id}`}>{p.stock>0?"View & add to bag →":"View product →"}</a></div></article>)}</div>}</div></section>
  <section className="offer-banner" id="offers"><div className="container offer-inner"><div><div className="eyebrow">03 / Just in</div><h2>{c("featured_title","Dress for the good days.")}</h2><p>{c("featured_text","Our festive edit is on its way. Beautiful silhouettes, rich details and styles made for celebrations.")}</p><a className="cta light" href="#shop">Explore the edit →</a></div>{content.featured_image?<div className="offer-orbit" style={{backgroundImage:`url(${content.featured_image})`,backgroundSize:"cover",backgroundPosition:"center"}}/>:<div className="offer-orbit"><span>FESTIVE<br/>2026</span></div>}</div></section>
  <section className="section story" id="about"><div className="container story-grid">{content.about_image?<div className="story-art" style={{backgroundImage:`url(${content.about_image})`,backgroundSize:"cover",backgroundPosition:"center"}}/>:<div className="story-art"><span>ARVIND<br/>DRESSES</span></div>}<div><div className="eyebrow">04 / Our story</div><h2>{c("about_title","From a trusted Mandsaur store to your screen.")}</h2><p>{c("about_text","Arvind Dresses brings together styles chosen with a simple idea: shopping for clothes should feel personal, easy and exciting.")}</p><a className="text-link" href="#contact">Get in touch →</a></div></div></section>
  <section className="newsletter"><div className="container newsletter-inner"><div><div className="eyebrow">Stay in the loop</div><h2>First look. New drops. Good things.</h2></div><div className="newsletter-form"><input placeholder="Your email address" type="email"/><button>Join us →</button></div></div></section>
  <footer className="footer" id="contact"><div className="container"><div className="footer-top"><div><a className="logo footer-logo" href="#"><span>ARVIND</span><small>DRESSES</small></a><p className="muted">{c("footer_text","Your fashion destination in Mandsaur, now online.")}</p></div><div><strong>Shop</strong><a href="#categories">Sarees</a><a href="#categories">Suits &amp; Sets</a><a href="#categories">Kurtis</a><a href="#categories">Dresses</a></div><div><strong>Help</strong><a href="#">Shipping &amp; delivery</a><a href="#">Returns policy</a><a href="#">Order support</a><a href="#contact">Contact us</a></div><div><strong>Visit us</strong><p className="muted">{c("address","Mandsaur, Madhya Pradesh, India")}</p>{content.phone&&<p className="muted">{content.phone}</p>}{content.email&&<p className="muted">{content.email}</p>}</div></div><div className="footer-bottom"><span>© 2026 Arvind Dresses. All rights reserved.</span><span>Made with care in Mandsaur.</span></div></div></footer>
 </main>;
}
